version: '2.1'
services:
  organization-ms:
    container_name: organization_ms
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile

    volumes:
      - ./go:/go/src/app 
      - SharedFolderContainers:/SharedStorage

    depends_on:
      organization-db:
        condition: service_healthy

    command: go run main.go

    environment:
      - GOPATH=/go
    ports:
      - "8000:8000"
  organization-db:

    container_name: organization_db
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    ports:
      - 5433:5432

volumes:
    SharedFolderContainers:
        external: true
